//go:build !ignore_autogenerated

/*
Copyright 2026 Alessandro Rontani

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Facet) DeepCopyInto(out *Facet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Facet.
func (in *Facet) DeepCopy() *Facet {
	if in == nil {
		return nil
	}
	out := new(Facet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Facet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetAccessPolicy) DeepCopyInto(out *FacetAccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetAccessPolicy.
func (in *FacetAccessPolicy) DeepCopy() *FacetAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(FacetAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FacetAccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetAccessPolicyList) DeepCopyInto(out *FacetAccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FacetAccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetAccessPolicyList.
func (in *FacetAccessPolicyList) DeepCopy() *FacetAccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(FacetAccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FacetAccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetAccessPolicySpec) DeepCopyInto(out *FacetAccessPolicySpec) {
	*out = *in
	in.Namespaces.DeepCopyInto(&out.Namespaces)
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetAccessPolicySpec.
func (in *FacetAccessPolicySpec) DeepCopy() *FacetAccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(FacetAccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetAggregateGroup) DeepCopyInto(out *FacetAggregateGroup) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]FacetAggregateKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Value.DeepCopyInto(&out.Value)
	if in.Contributors != nil {
		in, out := &in.Contributors, &out.Contributors
		*out = make([]FacetResourceProvenance, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetAggregateGroup.
func (in *FacetAggregateGroup) DeepCopy() *FacetAggregateGroup {
	if in == nil {
		return nil
	}
	out := new(FacetAggregateGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetAggregateKey) DeepCopyInto(out *FacetAggregateKey) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetAggregateKey.
func (in *FacetAggregateKey) DeepCopy() *FacetAggregateKey {
	if in == nil {
		return nil
	}
	out := new(FacetAggregateKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetAggregateMatch) DeepCopyInto(out *FacetAggregateMatch) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
	if in.Contributors != nil {
		in, out := &in.Contributors, &out.Contributors
		*out = make([]FacetResourceProvenance, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetAggregateMatch.
func (in *FacetAggregateMatch) DeepCopy() *FacetAggregateMatch {
	if in == nil {
		return nil
	}
	out := new(FacetAggregateMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetAggregateResourceFailure) DeepCopyInto(out *FacetAggregateResourceFailure) {
	*out = *in
	out.Provenance = in.Provenance
	out.Error = in.Error
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetAggregateResourceFailure.
func (in *FacetAggregateResourceFailure) DeepCopy() *FacetAggregateResourceFailure {
	if in == nil {
		return nil
	}
	out := new(FacetAggregateResourceFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetAggregateResult) DeepCopyInto(out *FacetAggregateResult) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]FacetAggregateGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Failures != nil {
		in, out := &in.Failures, &out.Failures
		*out = make([]FacetAggregateResourceFailure, len(*in))
		copy(*out, *in)
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(FacetResultError)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetAggregateResult.
func (in *FacetAggregateResult) DeepCopy() *FacetAggregateResult {
	if in == nil {
		return nil
	}
	out := new(FacetAggregateResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetAggregateValue) DeepCopyInto(out *FacetAggregateValue) {
	*out = *in
	if in.Matches != nil {
		in, out := &in.Matches, &out.Matches
		*out = make([]FacetAggregateMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetAggregateValue.
func (in *FacetAggregateValue) DeepCopy() *FacetAggregateValue {
	if in == nil {
		return nil
	}
	out := new(FacetAggregateValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetAggregation) DeepCopyInto(out *FacetAggregation) {
	*out = *in
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Precision != nil {
		in, out := &in.Precision, &out.Precision
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetAggregation.
func (in *FacetAggregation) DeepCopy() *FacetAggregation {
	if in == nil {
		return nil
	}
	out := new(FacetAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetDurationValue) DeepCopyInto(out *FacetDurationValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetDurationValue.
func (in *FacetDurationValue) DeepCopy() *FacetDurationValue {
	if in == nil {
		return nil
	}
	out := new(FacetDurationValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetField) DeepCopyInto(out *FacetField) {
	*out = *in
	if in.Operators != nil {
		in, out := &in.Operators, &out.Operators
		*out = make([]FacetOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetField.
func (in *FacetField) DeepCopy() *FacetField {
	if in == nil {
		return nil
	}
	out := new(FacetField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetFieldError) DeepCopyInto(out *FacetFieldError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetFieldError.
func (in *FacetFieldError) DeepCopy() *FacetFieldError {
	if in == nil {
		return nil
	}
	out := new(FacetFieldError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetFieldResult) DeepCopyInto(out *FacetFieldResult) {
	*out = *in
	if in.Matches != nil {
		in, out := &in.Matches, &out.Matches
		*out = make([]FacetTypedMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(FacetResultError)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetFieldResult.
func (in *FacetFieldResult) DeepCopy() *FacetFieldResult {
	if in == nil {
		return nil
	}
	out := new(FacetFieldResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetList) DeepCopyInto(out *FacetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Facet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetList.
func (in *FacetList) DeepCopy() *FacetList {
	if in == nil {
		return nil
	}
	out := new(FacetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FacetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetOperator) DeepCopyInto(out *FacetOperator) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(FacetOperatorOperand)
		(*in).DeepCopyInto(*out)
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]FacetOperatorOperand, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetOperator.
func (in *FacetOperator) DeepCopy() *FacetOperator {
	if in == nil {
		return nil
	}
	out := new(FacetOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetOperatorOperand) DeepCopyInto(out *FacetOperatorOperand) {
	*out = *in
	if in.StringValue != nil {
		in, out := &in.StringValue, &out.StringValue
		*out = new(string)
		**out = **in
	}
	if in.IntegerValue != nil {
		in, out := &in.IntegerValue, &out.IntegerValue
		*out = new(int64)
		**out = **in
	}
	if in.NumberValue != nil {
		in, out := &in.NumberValue, &out.NumberValue
		*out = new(string)
		**out = **in
	}
	if in.BooleanValue != nil {
		in, out := &in.BooleanValue, &out.BooleanValue
		*out = new(bool)
		**out = **in
	}
	if in.TimestampValue != nil {
		in, out := &in.TimestampValue, &out.TimestampValue
		*out = new(string)
		**out = **in
	}
	if in.DurationValue != nil {
		in, out := &in.DurationValue, &out.DurationValue
		*out = new(string)
		**out = **in
	}
	if in.QuantityValue != nil {
		in, out := &in.QuantityValue, &out.QuantityValue
		*out = new(string)
		**out = **in
	}
	if in.ObjectValue != nil {
		in, out := &in.ObjectValue, &out.ObjectValue
		*out = new(string)
		**out = **in
	}
	if in.ListValue != nil {
		in, out := &in.ListValue, &out.ListValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetOperatorOperand.
func (in *FacetOperatorOperand) DeepCopy() *FacetOperatorOperand {
	if in == nil {
		return nil
	}
	out := new(FacetOperatorOperand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetQuantityValue) DeepCopyInto(out *FacetQuantityValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetQuantityValue.
func (in *FacetQuantityValue) DeepCopy() *FacetQuantityValue {
	if in == nil {
		return nil
	}
	out := new(FacetQuantityValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetResourceProvenance) DeepCopyInto(out *FacetResourceProvenance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetResourceProvenance.
func (in *FacetResourceProvenance) DeepCopy() *FacetResourceProvenance {
	if in == nil {
		return nil
	}
	out := new(FacetResourceProvenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetResourceResult) DeepCopyInto(out *FacetResourceResult) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]FacetFieldResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(FacetResultError)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetResourceResult.
func (in *FacetResourceResult) DeepCopy() *FacetResourceResult {
	if in == nil {
		return nil
	}
	out := new(FacetResourceResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetResult) DeepCopyInto(out *FacetResult) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]FacetSourceResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetResult.
func (in *FacetResult) DeepCopy() *FacetResult {
	if in == nil {
		return nil
	}
	out := new(FacetResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetResultError) DeepCopyInto(out *FacetResultError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetResultError.
func (in *FacetResultError) DeepCopy() *FacetResultError {
	if in == nil {
		return nil
	}
	out := new(FacetResultError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetSource) DeepCopyInto(out *FacetSource) {
	*out = *in
	out.Resource = in.Resource
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = new(NamespaceSelection)
		(*in).DeepCopyInto(*out)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(ResourceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]FacetField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Aggregations != nil {
		in, out := &in.Aggregations, &out.Aggregations
		*out = make([]FacetAggregation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetSource.
func (in *FacetSource) DeepCopy() *FacetSource {
	if in == nil {
		return nil
	}
	out := new(FacetSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetSourceResult) DeepCopyInto(out *FacetSourceResult) {
	*out = *in
	if in.FieldErrors != nil {
		in, out := &in.FieldErrors, &out.FieldErrors
		*out = make([]FacetFieldError, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]FacetResourceResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Aggregates != nil {
		in, out := &in.Aggregates, &out.Aggregates
		*out = make([]FacetAggregateResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(FacetResultError)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetSourceResult.
func (in *FacetSourceResult) DeepCopy() *FacetSourceResult {
	if in == nil {
		return nil
	}
	out := new(FacetSourceResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetSpec) DeepCopyInto(out *FacetSpec) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]FacetSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetSpec.
func (in *FacetSpec) DeepCopy() *FacetSpec {
	if in == nil {
		return nil
	}
	out := new(FacetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetStatus) DeepCopyInto(out *FacetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(FacetSummary)
		**out = **in
	}
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = new(FacetResult)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetStatus.
func (in *FacetStatus) DeepCopy() *FacetStatus {
	if in == nil {
		return nil
	}
	out := new(FacetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetSummary) DeepCopyInto(out *FacetSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetSummary.
func (in *FacetSummary) DeepCopy() *FacetSummary {
	if in == nil {
		return nil
	}
	out := new(FacetSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacetTypedMatch) DeepCopyInto(out *FacetTypedMatch) {
	*out = *in
	if in.StringValue != nil {
		in, out := &in.StringValue, &out.StringValue
		*out = new(string)
		**out = **in
	}
	if in.IntegerValue != nil {
		in, out := &in.IntegerValue, &out.IntegerValue
		*out = new(int64)
		**out = **in
	}
	if in.NumberValue != nil {
		in, out := &in.NumberValue, &out.NumberValue
		*out = new(string)
		**out = **in
	}
	if in.BooleanValue != nil {
		in, out := &in.BooleanValue, &out.BooleanValue
		*out = new(bool)
		**out = **in
	}
	if in.TimestampValue != nil {
		in, out := &in.TimestampValue, &out.TimestampValue
		*out = (*in).DeepCopy()
	}
	if in.DurationValue != nil {
		in, out := &in.DurationValue, &out.DurationValue
		*out = new(FacetDurationValue)
		**out = **in
	}
	if in.QuantityValue != nil {
		in, out := &in.QuantityValue, &out.QuantityValue
		*out = new(FacetQuantityValue)
		**out = **in
	}
	if in.ObjectValue != nil {
		in, out := &in.ObjectValue, &out.ObjectValue
		*out = new(string)
		**out = **in
	}
	if in.ListValue != nil {
		in, out := &in.ListValue, &out.ListValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacetTypedMatch.
func (in *FacetTypedMatch) DeepCopy() *FacetTypedMatch {
	if in == nil {
		return nil
	}
	out := new(FacetTypedMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacePolicy) DeepCopyInto(out *NamespacePolicy) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SystemNamespaces != nil {
		in, out := &in.SystemNamespaces, &out.SystemNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacePolicy.
func (in *NamespacePolicy) DeepCopy() *NamespacePolicy {
	if in == nil {
		return nil
	}
	out := new(NamespacePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSelection) DeepCopyInto(out *NamespaceSelection) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSelection.
func (in *NamespaceSelection) DeepCopy() *NamespaceSelection {
	if in == nil {
		return nil
	}
	out := new(NamespaceSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRule) DeepCopyInto(out *ResourceRule) {
	*out = *in
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRule.
func (in *ResourceRule) DeepCopy() *ResourceRule {
	if in == nil {
		return nil
	}
	out := new(ResourceRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelector) DeepCopyInto(out *ResourceSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]v1.LabelSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelector.
func (in *ResourceSelector) DeepCopy() *ResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSelector)
	in.DeepCopyInto(out)
	return out
}
