apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubefacet.fullname" . }}-package
  namespace: {{ include "kubefacet.namespace" . }}
  labels:
    {{- include "kubefacet.labels" . | nindent 4 }}
  annotations:
    {{- include "kubefacet.ownershipAnnotations" . | nindent 4 }}
data:
  chart-version: {{ .Chart.Version | quote }}
  app-version: {{ .Chart.AppVersion | quote }}
  crd-facets-sha256: {{ index .Chart.Annotations "kubefacet.steeltanuki.it/generated-crd-facets-sha256" | quote }}
  crd-facetaccesspolicies-sha256: {{ index .Chart.Annotations "kubefacet.steeltanuki.it/generated-crd-facetaccesspolicies-sha256" | quote }}
  certificate-mode: {{ .Values.certificate.mode | quote }}
