apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubefacet.serviceAccountName" . }}
  namespace: {{ include "kubefacet.namespace" . }}
  labels:
    {{- include "kubefacet.labels" . | nindent 4 }}
  annotations:
    {{- include "kubefacet.ownershipAnnotations" . | nindent 4 }}
automountServiceAccountToken: true
